import type { Metadata } from 'next';
import './globals.css';
import '@fortawesome/fontawesome-svg-core/styles.css';

import { Geist, Geist_Mono } from 'next/font/google';

import { config } from '@fortawesome/fontawesome-svg-core';
import LayoutTopBar from './_components/LayoutTopBar';

config.autoAddCss = false;

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'LoveCare RickMorty Test',
  description:
    'Generated by create next app for simple creation of Rick and Morty character database',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LayoutTopBar />

        {children}
      </body>
    </html>
  );
}
